Redis cache refactor
pandamaroder/MvcWithRedis pull request #1
Opened 2024-08-12 20:34 UTC by pandamaroder

Add full coverage for all caches:
- books
- booksByCategory

Check the ability to manually add new persistent entity to the cache while creating and updating process

Add ReadMe about redis manual check

2024-08-12 21:47 UTC, pandamaroder commented
Gather BackLog tasks:
3.1 Add test for deleteBook from Cache booksByCategory
3.2 Add new cache manual eviction for deleteBook service method: realize the logic with createdAt parameter verififiction towards the depth of cache parameter

2024-08-13 07:26 UTC, mfvanek requested changes

2024-08-13 07:26 UTC, mfvanek commented on .github/workflows/github-actions-demo.yml
> +                image: redis:latest
Это здесь лишнее

2024-08-13 07:26 UTC, mfvanek commented on src/main/java/com/example/demo/model/ClockAwareEntityListener.java
> +            entity.setCreatedAt(LocalDateTime.now(ZoneId.systemDefault()));
Почему не используется `clock`?

2024-08-13 07:26 UTC, mfvanek commented on src/main/java/com/example/demo/services/BooksService.java
> +        final LocalDateTime endOfDay = onDate.atTime(LocalTime.now(ZoneId.systemDefault()));
Везде должны использоваться "системные" часы https://github.com/pandamaroder/MvcWithRedis/blob/b3ba9476240ed05d6cc72999b6c0634e2e7f1b9f/src/main/java/com/example/demo/config/ClockConfig.java#L12

Подробности в https://habr.com/ru/articles/681608/

2024-08-15 12:55 UTC, pandamaroder commented on .github/workflows/github-actions-demo.yml
> +                image: redis:latest
@mfvanek получаю ошибку https://github.com/pandamaroder/MvcWithRedis/actions/runs/10404050702/job/28811715493

2024-08-16 07:02 UTC, mfvanek commented on src/test/java/com/example/demo/RedisInitializer.java
> +            "spring.redis.url=" + redisUrl
Это неправильно. В основном конфиге выставляется spring.data.redis

2024-08-16 07:02 UTC, mfvanek commented on .github/workflows/github-actions-demo.yml
> +    services:
Это неправильно. Никакой работы с контейнерами здесь не должно быть

2024-08-16 07:03 UTC, mfvanek requested changes
Нужно Исправить работу с Redis в тестах и CI

2024-08-17 17:13 UTC, mfvanek requested changes
Нужно исправить работу с редис в тестах

2024-08-18 17:39 UTC, pandamaroder commented on .github/workflows/github-actions-demo.yml
> +    services:
почему не должно?

2024-08-19 06:21 UTC, mfvanek approved these changes

2024-08-19 06:21 UTC, mfvanek requested changes
Тесты не проходят

2024-08-19 06:28 UTC, mfvanek commented on src/test/java/com/example/demo/RedisInitializer.java
> +        REDIS_CONTAINER.start();
Здесь нужно настроить контекст приложения, чтобы они могло подключиться к запущенному контейнеру.
Внимательно изучите документацию на Testcontainers https://java.testcontainers.org/features/networking/
Вам нужно правильно пробросить порт

2024-08-19 06:30 UTC, mfvanek commented on src/test/java/com/example/demo/RedisInitializer.java
> +        REDIS_CONTAINER.start();
Так же стоит вернуться к Docker
https://www.youtube.com/watch?v=TJg7QpqCH70
https://www.youtube.com/watch?v=0mil0KBK4Tw

2024-08-19 13:32 UTC, mfvanek commented on .github/workflows/github-actions-demo.yml
> +    services:
Контейнер с Redis должен подниматься из приложения.
Пайплайн ничего не должен об этом знать.

2024-08-19 13:35 UTC, mfvanek commented on .github/workflows/github-actions-demo.yml
> +                image: redis:latest
@pandamaroder Неправильно настроена работа с Redis. В Спринг-контекст не проброшены нужные параметры для подключения к Redis

2024-08-19 20:16 UTC, pandamaroder commented on .github/workflows/github-actions-demo.yml
> +                image: redis:latest
@mfvanek подключение удалось только при использовании GenericContainer, последни билд успешный https://github.com/pandamaroder/MvcWithRedis/actions/runs/10460273409

2024-08-19 20:19 UTC, pandamaroder commented on .github/workflows/github-actions-demo.yml
> +                image: redis:latest
Не очевидная проблема, почему не работает RedisContainer? Возможно настройки?? 

Нерабочий конфиг так выглядит: 

`  @Container
    private static final RedisContainer REDIS_CONTAINER = new RedisContainer(DockerImageName.parse("redis:6.2.6")).withExposedPorts(6379);


    @Override
    public void initialize(ConfigurableApplicationContext context) {

        REDIS_CONTAINER.start();

        TestPropertyValues.of(
                "spring.redis.host=" + REDIS_CONTAINER.getRedisHost(),
                "spring.redis.port=" + REDIS_CONTAINER.getRedisPort()
        ).applyTo(context.getEnvironment());

    }`

2024-08-19 20:21 UTC, pandamaroder commented on .github/workflows/github-actions-demo.yml
> +                image: redis:latest
ок: 

` @Container
    private static final GenericContainer<?> CONTAINER = new GenericContainer<>(DockerImageName.parse("redis").withTag("4.0.14"))
            .withExposedPorts(6379);

    @Override
    public void initialize(ConfigurableApplicationContext context) {
        CONTAINER.start();

        TestPropertyValues.of(
                "spring.data.redis.host=" + CONTAINER.getHost(),
                "spring.data.redis.port=" + CONTAINER.getMappedPort(6379)
        ).applyTo(context.getEnvironment());
    }`

2024-08-19 20:22 UTC, pandamaroder commented on .github/workflows/github-actions-demo.yml
> +    services:
@mfvanek готово

2024-08-19 20:34 UTC, pandamaroder commented on src/test/java/com/example/demo/RedisInitializer.java
> +        REDIS_CONTAINER.start();
@mfvanek c экспонированием портов контейнера вроде понятно, что Порты, которые экспонируются принудительно, будут привязаны к случайным свободным портам на хосте. Поэтомунужно запросить фактический порт хоста у Testcontainers с помощью метода getMappedPort

2024-08-19 20:36 UTC, pandamaroder commented on src/test/java/com/example/demo/RedisInitializer.java
> +        REDIS_CONTAINER.start();
но https://github.com/pandamaroder/MvcWithRedis/pull/1#discussion_r1722304529

2024-08-19 20:42 UTC, pandamaroder commented on .github/workflows/github-actions-demo.yml
> +                image: redis:latest
доп. инфо по редис контейнеру, то что getRedisPort() возвращает фактический порт на который экспонировался заданный принудительно 

@Override
	public int getRedisPort() {
		return getFirstMappedPort();
	}

2024-08-20 06:02 UTC, mfvanek approved these changes

2024-08-20 08:23 UTC, pandamaroder commented on src/test/java/com/example/demo/RedisInitializer.java
> +        REDIS_CONTAINER.start();
@mfvanek что вы думаете по этому https://github.com/pandamaroder/MvcWithRedis/pull/1#discussion_r1722304529

2024-08-20 08:59 UTC, mfvanek commented on .github/workflows/github-actions-demo.yml
> +                image: redis:latest
Не вижу проблемы. Всё работает
```java
public class RedisInitializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {

    private static final RedisContainer CONTAINER = new RedisContainer(DockerImageName.parse("redis").withTag("6.2.6"))
            .withExposedPorts(6379);

    @Override
    public void initialize(ConfigurableApplicationContext context) {
        CONTAINER.start();

        TestPropertyValues.of(
                "spring.data.redis.host=" + CONTAINER.getRedisHost(),
                "spring.data.redis.port=" + CONTAINER.getRedisPort()
        ).applyTo(context.getEnvironment());
    }
}
```

2024-08-20 08:59 UTC, mfvanek commented on src/test/java/com/example/demo/RedisInitializer.java
> +        REDIS_CONTAINER.start();
Ответил https://github.com/pandamaroder/MvcWithRedis/pull/1#discussion_r1722953073

2024-08-20 11:10 UTC, pandamaroder commented on .github/workflows/github-actions-demo.yml
> +                image: redis:latest
@mfvanek  билд удаленный не работает

2024-08-20 11:36 UTC, pandamaroder commented on .github/workflows/github-actions-demo.yml
> +                image: redis:latest
как будто есть ошибка  из-за которой передача строки с тегом ("redis:6.2.6") работает некорректно

2024-08-20 14:41 UTC, mfvanek commented on .github/workflows/github-actions-demo.yml
> +                image: redis:latest
@pandamaroder 

Стоит попробовать вот так: убрать withExposedPorts

```java
public class RedisInitializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {

    private static final RedisContainer CONTAINER = new RedisContainer(DockerImageName.parse("redis:7.4.0"));

    @Override
    public void initialize(ConfigurableApplicationContext context) {
        CONTAINER.start();

        TestPropertyValues.of(
                "spring.data.redis.host=" + CONTAINER.getRedisHost(),
                "spring.data.redis.port=" + CONTAINER.getRedisPort()
        ).applyTo(context.getEnvironment());
    }
}
```

2024-08-21 16:23 UTC, pandamaroder commented on .github/workflows/github-actions-demo.yml
> +                image: redis:latest
https://github.com/pandamaroder/MvcWithRedis/actions/runs/10486688824

2024-08-22 06:50 UTC, mfvanek commented on .github/workflows/github-actions-demo.yml
> +                image: redis:latest
В логах ничего нет. Причина ошибки неясна. Можно включить расширенное логирование для отдельных пакетов (редис контейнер и тестконтейнерс) и посмотреть, что происходит

2024-09-12 14:42 UTC, merged